In [7]:
import numpy as np
from scipy.stats import entropy

In [7]:
a = np.array([0.1,0.5,0.3,0.1])

In [11]:
b = np.array([0.15,0.6,0.2,0.05])
c = np.array([0.15,0.4,0.4,0.05])

In [12]:
(a * b * c) / np.sum(a*b*c)

array([0.01535836, 0.81911263, 0.16382253, 0.00170648])

In [18]:
(((a * b) / np.sum(a*b)) * c) / np.sum((((a * b) / np.sum(a*b)) * c))

array([0.02316602, 0.23166023, 0.74131274, 0.003861  ])

In [19]:

bla = np.array([[0.4,0.5,0.05,0.05], [0.6,0.4,0.1,0.1], [0.3,0.65,0.025,0.025]])

In [20]:
bla.shape

(3, 4)

In [21]:
avg = np.mean(bla, axis=0)
print(avg)

[0.43333333 0.51666667 0.05833333 0.05833333]


In [22]:
entropy(avg)

1.034922862936771

In [23]:
bla2 = np.array([[0.4,0.5,0.05,0.05], [0.6,0.4,0.1,0.1], [0.3,0.65,0.025,0.025], [1.0, 0, 0, 0]])

In [24]:
avg2 = np.mean(bla2, axis=0)
print(avg2)

[0.575   0.3875  0.04375 0.04375]


In [25]:
entropy(avg2)

0.9624781279265817